# SPDX-FileCopyrightText: 2020 Lukas Schrangl <lukas.schrangl@tuwien.ac.at>
#
# SPDX-License-Identifier: BSD-3-Clause

{% set name = "sdt-python" %}
{% set version = "17.1" %}
{% set hash = "b5cadee5c34697a03cd0ef42e49cfc706c283d6608a6eff4a02d1c8d80ca6303" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/schuetzgroup/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ hash }}

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    noarch: python

requirements:
    host:
        - python
        - pip
    run:
        - python >=3.7
        - numpy >=1.10
        - pandas
        - pytables
        - opencv
        - pyyaml
        - pims >=0.3.0
        - numba
        - qtpy >=1.1
        - matplotlib-base
        - pywavelets >=0.3.0
        - scipy >0.18
        - tifffile >=0.14.0

test:
    requires:
        - pytest
        - trackpy
        - lmfit
        - scikit-learn
        - imageio
    commands:
        - pytest -v tests
    source_files:
        - tests
    imports:
        - sdt
        - sdt.brightness
        - sdt.changepoint
        - sdt.flatfield
        - sdt.fret
        - sdt.helper
        - sdt.image
        - sdt.io
        - sdt.loc
        - sdt.motion
        - sdt.multicolor
        - sdt.optimize
        - sdt.roi
        - sdt.sim
        - sdt.spatial

about:
    home: https://github.com/schuetzgroup/sdt-python
    license: BSD-3-Clause
    license_file:
        - LICENSES/BSD-3-Clause.txt
        - LICENSES/CC-BY-4.0.txt
        - LICENSES/CC0-1.0.txt
        - LICENSES/LGPL-3.0-or-later.txt
        - LICENSES/LicenseRef-Matplotlib-1.3.txt
        - LICENSES/MIT.txt
        - sdt/gui/breeze-icons/COPYING-ICONS
    summary: "Tools for fluorescence microscopy data analysis"
    dev_url: https://github.com/schuetzgroup/sdt-python
    doc_url: https://schuetzgroup.github.io/sdt-python

extra:
    recipe-maintainers:
        - lschr
